### ISSUE TITLE
Be able to schedule the client delivery status changes

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#313]
### Expected Behaviour

I should be able to change a client meal's status at a date further in time.
Example: _Mme Michu will pause her deliveries from 1st september to 15th september._

### Actual Behaviour

The status can be changed and is immediately effective.

**Comment by erozqba** [comment]
I will reopen this issue because the current merged solution can ( I think that should) be improved.
The current solution has the following problems:
- No form validation.
- Anonymous users can send a POST request to the route and add new scheduler.
- Two differents URL when this can be handled with a single one.
We should be able to reuse more tools in the Django framework and make this more secure.
