### ISSUE TITLE
ORM and complex reporting queries

### ISSUE THREAD

**Issue by lamontfr** [savoirfairelinux/sous-chef#339]
On Monday August 8th, on the #feastproject IRC, Ernesto asked why we
were using SQLAlchemy in the SousChef project. David also said that it
was peculiar to have two ORMs in the project and wondered why we could
not use only the Django ORM. I explained that I used SQLAlchemy for
complex queries (for example the KitchenCount report) in order to
avoid using "raw" sql. I also said that I was going to think it over
and here is what I propose.

Summary
- Code clarity is the main objective
- Use the Django ORM everywhere except for complex queries for which
raw SQL or long chains of "select_related / prefetch_related" would be
required to avoid multiple database hits
- Use SQLAlchemy Core for selects in complex queries only, but do not
use SQLAlchemy ORM
- Do not use raw SQL

Rationale
- The SQL language was designed especially for "reporting" queries
where many columns are assembled from many tables joined together
using a combination of logic comparisons
- The database engine is optimized for executing complete queries by
itself and does a better job at it than a iterative procedure
- Most developers can read or understand SQL selects
- Explicit is better than implicit
- We could write code using the Django ORM for complex queries, but we
will lose in readability and in the end Django will have to figure out
the SQL to generate which we may have to check to verify its behavior
- Raw SQL is not always portable between different database backends
- SQLAlchemy has two distinct components : SQLALchemy Core and
SQLAlchemy ORM, the latter is built on top of the former.
- The SQLALchemy Core expression language syntax is very close to pure SQL
- The aldjemy package handles the seamless usage of SQLAlchemy inside
a Django project, by reflecting the models and by integrating with the
Django database connection.

Actions
- [X] Modify SousChef Kitchen Count Report queries to use only
SQLAlchemy core. (See order/models.py PR 338)
- [ ] Update Contribution Guidelines to add the rule about the use of
Django ORM and the special conditions where SQLALchemy Core is
allowed.

**Comment by lamontfr** [comment]
Here is some additional information from external sources : 

1- A thread (June 2012) on the Django Developers forum
https://groups.google.com/forum/#!topic/django-developers/0IuJssTt8tc
See the first post by Luke Plant and especially section "==Motivation 1", on the second page.
He is a core Django contributor https://github.com/django/django/graphs/contributors ( spookylukey #9 ) 

2- A short blog post (October 2015) that explains the need and the solution
http://nicolovaligi.com/sql-alchemy-queries-in-django.html

**Comment by cormier** [comment]
Thanks François.

I disagree with the proposal and still believe that using sqlalchemy should be removed from the project.

> - The SQL language was designed especially for "reporting" queries
where many columns are assembled from many tables joined together
using a combination of logic comparisons
- The database engine is optimized for executing complete queries by
itself and does a better job at it than a iterative procedure

This is true, but performance is not an issue at this point. There are reasons to believe that for the usage patterns of Santropol, an "iterative procedure" using the Django ORM will be fast enough. If it is not, there are many ways of improving the performance using only standard features of Django: for example, we could cache the results, or introduce a management command to pre-generate the kitchen counts during a period where the system is not intensively used.

> - Most developers can read or understand SQL selects

Yes, and this is why in the worst case I would prefer a raw sql query
than introducing a second ORM. :-)

> - We could write code using the Django ORM for complex queries, but we
will lose in readability

I am not certain that we will really lose in readability. 

I agree that code readability is an issue and there are many actions we should take to improve it. For example, the get_kitchen_count method we are discussing should be documented and the function should be broken down in smaller testable functions. In my opinion the major code readability issues of the project are unrelated to the use of the ORM. 

> and in the end Django will have to figure out the SQL to generate which we may have to check to verify its behavior

All code should be tested, but if we use a framework, we need to trust it. I trust the Django ORM the same way I trust its middleware framework, its password salting strategy or its url resolution functions.

> - Raw SQL is not always portable between different database backends

This is true but in my opinion this issue is minor and theoretical. What will most probably happen is that we will choose a database backend and stick with it.

> - SQLAlchemy has two distinct components : SQLALchemy Core and SQLAlchemy ORM, the latter is built on top of the former.
> - The SQLALchemy Core expression language syntax is very close to pure
SQL

I dont find this true. Even a seasoned python developer with experience in sqlalchemy will need some effort to wrap her head around the sqlalchemy particularities and understand what the code does. A raw sql query in the one odd case where the Django ORM is not enough could be simpler than code that use sqlalchemy.

> 1- A thread (June 2012) on the Django Developers forum https://groups.google.com/forum/#!topic/django-developers/0IuJssTt8tc See the first post by Luke Plant and especially section "==Motivation 1", on the second page. He is a core Django contributor https://github.com/django/django/graphs/contributors ( spookylukey # 9 )

The author argues for replacing the Django ORM with Sqlalchemy. This could be interesting for Django 2.0, but this is not the issue we are discussing. What we are considering here is using sqlalchemy alongside the Django ORM. On that topic, the author clearly writes that this is a "painful" solution.

If we have no choice but to use a "poor" or "painful" solution, I would rather use one that has the most minimal impact on the project and the capacity of other Django developers to join us, and for this reason I believe we should opt for a solution that only involves components from the Django framework.

**Comment by manumilou** [comment]
SQLAlchemy dependency has been removed in #473 . Raw SQL is now used.
