### ISSUE TITLE
Allow minifying / compressing the static assets (JS and CSS)

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#385]
### Expected Behaviour

For better performances and optimisation:
* Javascript files should be served in one compressed and minified Javascript file.
* CSS files should be served in one compressed and minified Javascript file.

### Actual Behaviour

The files are served as is.

### Steps to reproduce

* Load a page with a network debugger opened
* Observe the several HTTP requests, one per file

**Comment by Microserf** [comment]
[Grunt](http://gruntjs.com/) would be a useful tool to create a build process for static assets -- minimization, concatenation, uglification, CDN substitution, etc.

Its inclusion into the project would require some guidance from the architecture team, however, especially since it would add a few new dependencies to the development environment (which wouldn't be trackable with `pip`).

Additionally, an extra step would be added to the build process.

**Comment by erozqba** [comment]
I had made some work to add [Gulp](http://gulpjs.com/) to the project in order to create a build process for static assets -- minimization, concatenation, uglification, CDN substitution, etc.

The main goal is to have the tools and the place where frontend developments files will be grouped making the maintenance and changes in easier. 

This will add new dependencies to the development environment which wouldn't be trackable with `pip` but will be trackable with `npm` and will be only needed if you have to modify the frontend of the application `images / css / javascript`.
