### ISSUE TITLE
Discussions around deployment solutions

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#439]
### Expected Behaviour

We should have a rather generic solution to deploy the application.
Even though the application won't be on internet @Santropool, it may be different for other *popottes*.

### Actual Behaviour

Dockerized application, run with a development server.

**Comment by erozqba** [comment]
I have proposed some changes to use a dockerized application that runs "Gunicorn + Nginx" instead of the development server, we can continue to use the development server in dev environments.

**Comment by madmath** [comment]
I think using Docker is a very nice development/deployment solution (Thanks for setting it up Ernesto!). However, I'd like to discuss the needs of the customer as to the actual server this will be deployed on.

So far I gather the requirements are the following (most important first):
1. Data security (sensitive info in DB) 
2. Proper authentication/authorization model.
3. Ease of update and deployment for the customer/IT person.
4. Consistency regardless of development environment and production environment.

@manumilou @erozqba @lamontfr What do you think? 

I think an on-premise server (e.g. at Santropol) doesn't really address point 1, since encryption, even though it can be achieved, will be defeated with a passphrase which could be obtained by social engineering or otherwise. I think we should be looking for a hosting/cloud provider that encrypts data at rest. Combined with HTTPS for encrypted data in transit, there's a pretty good story for data security.

Point 2 is relatively well served with Django user authentication and its authorization model. 

Point 3 it really depends on the customer and their ability to run Docker commands, but I would think it won't be too hard with the proposed Docker setup.

Point 4 we get for free with Docker ;)

**Comment by lamontfr** [comment]
@madmath 

- I agree with your list of deployment requirements.
- I also think that hosting the production environment at a reliable provider would be more secure than on premises which is vulnerable to digital and also physical theft. Since Santropol Roulant have an IT specialist on staff, we could (1) involve him in the analysis of the pros and cons and (2) propose that he would have admin rights on the hosted environment so he can remain in control.
- Personal data has to be protected according to Law; the Santropol management must be well informed to make the best decision.

**Comment by madmath** [comment]
@lamontfr Agreed wrt. the IT specialist. Ideally Santropol Roulant would have the relationship with the hosting provider and manage the deployments according to a procedure.
