### ISSUE TITLE
Improve the way the order items are handled

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#471]
### Expected Behaviour

It should be easy to create new orders from the web interface.
It should be easy to create new order items from the web interface.

### Actual Behaviour

It is complicated. Lot of conditional fields are always displayed. Prices are not always computed properly.

**Comment by manumilou** [comment]
Questions regarding the modelisation:

- free_quantity: pourquoi?
- price: est-ce un prix unitaire ?
- Le flag Billable est le seul critère qui nous permet de savoir si on doit charger l'item ? ou le order_item_type rentre en compte ?
- Est-ce que les order_item_types peuvent être changés ? Impact sur le kitchen count ? Génération des commandes ?

Réponses:

1- free_quantity :

Ceci est nécessaire dans le cas où le client s'entend avec le CM (client manager) pour obtenir une compensation, par exemple une "main dish" ou "side dish" gratuit lorsqu'un plat a été perdu ou substitué par erreur lors d'une livraison précédente.

2- price :

C'est le prix calculé = (total_quantity - free_quantity) * unit_price,
où unit_price dépend du "rate_type". Le code est comme suit (voir
order/models.py create_orders_on_defaults() :

            if client.rate_type == RATE_TYPE_LOW_INCOME:
                main_price = MAIN_PRICE_LOW_INCOME
                side_price = SIDE_PRICE_LOW_INCOME
            elif client.rate_type == RATE_TYPE_SOLIDARY:
                main_price = MAIN_PRICE_SOLIDARY
                side_price = SIDE_PRICE_SOLIDARY
            else:
                main_price = MAIN_PRICE_DEFAULT
                side_price = SIDE_PRICE_DEFAULT

Les prix sont "hard coded" dans order/models.py. Il faudrait demander
les bons montants à Jean-François. Éventuellement, je crois cela
devrait être dans une table de paramètres dans la BD.

MAIN_PRICE_DEFAULT = 8.00
SIDE_PRICE_DEFAULT = 1.00
MAIN_PRICE_LOW_INCOME = 7.00
SIDE_PRICE_LOW_INCOME = 0.75
MAIN_PRICE_SOLIDARY = 6.00
SIDE_PRICE_SOLIDARY = 0.50

3- billable_flag :

Je ne l'utilise pas nulle part. Ceci est redondant avec le
order_item_type. Ce champ pourrait être enlevé.

4- order_item_type :

Le premier caractère nous dit si c'est facturable="B" ou non-facturable="N".

ORDER_ITEM_TYPE_CHOICES = (
    ('', _('Order item type')),
    ('B component',
     _('BILLABLE meal component (main dish, side dish)')),
    ('B delivery',
     _('BILLABLE delivery (general store item, ...)')),
    ('N delivery',
     _('NON BILLABLE delivery (ex. invitation card, ...)')),
    ('N pickup',
     _('NON BILLABLE pickup (payment)')),


Ceci n'est pas utilisé dans le Kitchen Count. Leur contenu et
sémantique peuvent être modifiés pour les besoins du "billing".

La seule constante à conserver est ORDER_ITEM_TYPE_CHOICES_COMPONENT,
mais sa valeur peut varier. Donc si un order_item est un plat
principal ou un plat secondaire, il faut que son order_item_type soit
== ORDER_ITEM_TYPE_CHOICES_COMPONENT.

**Comment by manumilou** [comment]
@lamontfr : here all proposals:

1. Deleting _free_quantity_. To *offer* an item, the CM can create a new non billable item instead.

2. Ok for the unit price. But: order creation form does not use this, but the price. And yes it could be nice to add the rates in the database. One place in particular ?

3. billable_flag will be used to identify billable items.

4. Do you use the first letter to determine if the item is billable or not ? I didn't see that anywhere. It seems to be just a label.

**Comment by lamontfr** [comment]
@manumilou 

- (1) I agree.

- (2a) The order item contains the price that will be billed (if the item is billable). When the CM creates a order item we could have a button that calculates the price based on the client rate type and the quantity; the CM can override this price if he wants to.

- (2b) We could store the rates in a new  table named Parameter (id, name, value). It will be even more useful when we eventually have other MealsOnWheels / Popotes using SousChef ) not just Santropol Roulant, such that we can store things in the DB like organization name, logo etc. and keep only one code base. We would then load the value of constants (such as MAIN_PRICE_LOW_INCOME) from the DB on app initialization. The code will still use constants rather than refer to the DB.

- (3) I Agree.

- (4) I do not use the first character of order_item_type. It was just an idea.

Please let me know what you decide.
