### ISSUE TITLE
Strings unsuited for translation

### ISSUE THREAD

**Issue by PascalPriori** [savoirfairelinux/sous-chef#509]
Some strings are unsuited for translation.
See on transifex:
* Non translated item : https://www.transifex.com/savoirfairelinux/sous-chef/translate/#fr/$/96594708?translated=no
* Non reviewed item : https://www.transifex.com/savoirfairelinux/sous-chef/translate/#fr/$/96222944?reviewed=no

Example : 
Transifex propose to translate separatly  "is an" "client on the" "route" in the sentence 
(CLIENTNAME) is an (Ongoing) client on the (ROUTENAME) route 
Translation should be : (CLIENTNAME) est un client (Régulier) sur la route (ROUTENAME) 
Go to transifex : https://www.transifex.com/savoirfairelinux/sous-chef/translate/#fr/$/96594660?translated=no

**Comment by ssirois** [comment]
OK.

The issue is that concatenation of translated strings and variables has been used to build sentences like so in templates:

```
<p>{{ obj.member.firstname }} {% trans "is an" %} 
    <strong>{{ obj.get_delivery_type_display }}</strong>
    {% trans "client on the" %} <strong>{{ obj.route }}</strong> {% trans "route" %}.</p>
```

I thing the use of the [blocktrans template tag](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/#blocktrans-template-tag) would be more appropriated and would give the opportunity to translate properly full sentences instead. e.g.: by having the possibility of moving the variables around in a translated sentence.

**Comment by ssirois** [comment]
@PascalPriori I have started something on my branch ( ssirois/santropol-feast@ff12c8b423b28e8fa9c4a49553e285da9d4ea98c )

@manumilou what would be the better approach for me to give @PascalPriori access to this new string in http://transifex.com/ so that I can receive feedback and adjust for "all templates"?
