### ISSUE TITLE
Provide an early alert about the client's dishes to avoid

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#603]
### Expected Behaviour

Alert the "Customer manager" at least a week ahead of time of all clients that have an ongoing order for a meal on a date for which they would refuse the main dish. The customer manager would then be able to call each such client and recommend that he changes the date and maybe also the quantity of the meal delivery.

### Actual Behaviour

This field is ignored, e.g. in kitchen count (http://localhost:8000/delivery/kitchen_count/). Nothing special is done for it.

### Steps to reproduce

1. Add "dishes to avoid" on one client.
2. Go to kitchen count, generate orders, select that main dish.
3. Proceed to the next step. 

### Note

**SRoulant is not certain that they will want to offer this premium service. This functionality is on hold for now. When data conversion is completed, we will see the number of current clients that have mentioned dishes to avoid.**

**Comment by lamontfr** [comment]
@lingxiaoyang The client's dishes to avoid will be used to alert the "Customer manager" at least a week  ahead of time of all clients that have an ongoing order for a meal on a date for which they would refuse the main dish. The customer manager would then be able to call each such client and recommend that he changes the date and maybe also the quantity of the meal delivery. This requires that the database includes the daily menu (main dish) from the SRoulant yearly calendar, which is not yet the case. It is also a "premium" service that SRoulant is not certain that they will want to offer. So this functionality is on hold for now. When data conversion is completed, we will see the number of current clients that have mentioned dishes to avoid.

I understand well your remark about this since the initial version of the kitchen count that I wrote included reporting the clashes with the client's dishes to avoid, but this was removed recently at the request of SRoulant because it is too late to tell the cook in the morning that a client needs a completely different main dish for that day.

**Comment by lingxiaoyang** [comment]
@lamontfr I understand. Thanks for explaining!

Do I close this issue, or simply put a "wont-fix" label on it?

**Comment by lamontfr** [comment]
@lingxiaoyang If you agree, I think you could rename the issue to be "Provide an early alert about the client's dishes to avoid".
 So, the expected behaviour could become "Alert the "Customer manager" at least a week ahead of time of all clients that have an ongoing order for a meal on a date for which they would refuse the main dish. The customer manager would then be able to call each such client and recommend that he changes the date and maybe also the quantity of the meal delivery."

But make sure you mention that "SRoulant is not certain that they will want to offer this premium service. This functionality is on hold for now. When data conversion is completed, we will see the number of current clients that have mentioned dishes to avoid."

**Comment by lingxiaoyang** [comment]
Is this issue still valid? See PR #648

**Comment by lamontfr** [comment]
@lingxiaoyang @manumilou I think the point should be addressed and decided upon at the next meeting with SRoulant which is scheduled for March 1st. I will forward the question to Jean-François ahead of time.

**Comment by lamontfr** [comment]
@lingxiaoyang @manumilou I received a confirmation from Jean-François (2017-02-28 11:36) that this is not required anymore, because SRoulant will not offer this service in any foreseeable future.
