### ISSUE TITLE
Client form: ui search doesn't pop up search results when there are only 1 or 2 characters

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#672]
### Expected Behaviour

In the client creation/modification form, the `ui search` fields should respond as soon as a user types a character.

### Actual Behaviour

In reality, the search result doesn't pop up before there are 3 characters. Example:

1 character (doesn't pop up):
![image](https://cloud.githubusercontent.com/assets/8630726/23221404/fec9af68-f8f2-11e6-9adf-aad364aab5b2.png)

2 characters (doesn't pop up):
![image](https://cloud.githubusercontent.com/assets/8630726/23221413/06e2fa38-f8f3-11e6-9a53-f0248204cd18.png)

3 characters (pop up with a result):
![image](https://cloud.githubusercontent.com/assets/8630726/23221423/101c84fc-f8f3-11e6-8849-2f94367a2907.png)

Another example:
1 character (doesn't pop up):
![image](https://cloud.githubusercontent.com/assets/8630726/23221446/20b94fe8-f8f3-11e6-8141-d3f576da1750.png)
2 characters (doesn't pop up):
![image](https://cloud.githubusercontent.com/assets/8630726/23221457/28eb8802-f8f3-11e6-9613-022800d84b22.png)
3 characters (pop up: no result):
![image](https://cloud.githubusercontent.com/assets/8630726/23221465/317234da-f8f3-11e6-8d4c-cf7619925d98.png)

### Steps to reproduce

* step 1: go to client form (either creating a new client or editing an existing client)
* step 2: go to "referent", "payment" or "emergency contact"
* step 3: try out the search field.

I'm not sure why it happens. Please inform if this issue doesn't occur at your side.

**Comment by lingxiaoyang** [comment]
It seems because of the code here:
https://github.com/savoirfairelinux/sous-chef/blame/0e8f48ae2f2263c9ffb3fa293f82236cca849006/src/frontend/js/member.js#L140

This setting concerning 3 characters has been there for a long time. Do we have a specific reason for this? If not, we can perhaps remove it as it causes an inconsistent behavior on the search field.

**Comment by erozqba** [comment]
@lingxiaoyang I think it was me the one that specifies at least 3 characters to start making request to look for clients, for reasons about this you can look here: http://ux.stackexchange.com/a/78937
I don't think this is an issue at all, and I don't see why this causes inconsistent behavior on the search field, can you give me some examples?

**Comment by aaboffill** [comment]
@lingxiaoyang and @manumilou this is easy to change because is a simple configuration value. The main issue is to take the correct decision. There are some things to think before to take the final decision:
* Now the database process is easy and quickly, but in the future the list of members could be increase to `100 000`, `500 000` or perhaps `1 000 000`. We will force the database to make a query from one or two characters whose result will be probably not used. 
* Now the result is limited to 20 member by response, it's very probably that we need to continue writing more than (one or two characters) to reduce the number of results until we can find the member.

I understand the point of @lingxiaoyang , maybe we need to add a placeholder to inform that you need to write more than x characters to get results. 

But if finally the decision is to decrease the minimum of the required characters, I vote by `at least one 2 characters` and show a placeholder with information.  

Otherwise with a placeholder could be enough to improve the UI.

**Comment by lingxiaoyang** [comment]
@erozqba  "inconsistent" - In my view, it's possible that we only remember a syllable of someone's name, e.g. "Da" in "Daniel". In this case, I tried to put two letters in the search box but nothing popped up, and I found when I put three letters there were search results. To me, this behavior was a bit strange because I was not sure if an error had occurred.

@aaboffill  A placeholder is a good idea.

**Comment by aaboffill** [comment]
@lingxiaoyang and @manumilou we can finally fix this issue with a descriptive placeholder?? If the answer is true I can make the task.
Regards...

**Comment by lingxiaoyang** [comment]
@aaboffill  I think we can. Let's go ahead.

**Comment by JeanFrancoisFournier** [comment]
Some of our former clients of asian descent have some really short last names (ie. Ng, Lu, Yu) This could be a problem.
