### ISSUE TITLE
Scheduled status modifications can not be deleted

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#685]
### Expected Behaviour

As a system administrator or staff member, I should be able to delete a scheduled status change for a client, from the client's view (Ex: http://localhost:8000/member/view/<client_id>/status)

### Actual Behaviour

As a system administrator or staff member, I cannot delete a scheduled status change for a client, from the client's view (Ex: http://localhost:8000/member/view/<client_id>/status)

### Steps to reproduce

* Go a client's view
* Schedule a status change by using the status button, at the top-right
* Try to delete the future status change

**Comment by JeanFrancoisFournier** [comment]
Within the UI, we should be able to:
1# Cancel a future scheduled status change (i.e. client calls to cancel his planned vacation due to family emergency)
2# Cancel a current (ongoing) scheduled status change (client changes his mind in the middle of a meal delivery pause)
3# Lengthen a current (ongoing) scheduled status change (ie. prolonged hospitalisation)
4# Shorten a current (ongoing) scheduled status change (i.e Client is released from jail early for good conduct)

**Comment by JeanFrancoisFournier** [comment]
#5 Lengthen a future scheduled status change
#6 Shorten a future scheduled status change

**Comment by lingxiaoyang** [comment]
@aaboffill  I copied JF's two comments to issue #717 for more discussion. For now we can accept your PR #711.
