### ISSUE TITLE
As an admin, I should be able to specify meals defaults for every clients for every day

### ISSUE THREAD

**Issue by manumilou** [savoirfairelinux/sous-chef#688]
### Expected Behaviour

In the client's preferences edit view, as an administrator or a staff member, I should be able to select meals defaults for an ongoing client even if no delivery is scheduled for a given week day.

### Actual Behaviour

For an ongoing client, as an administrator or a staff member, I can only specify meals defaults for delivery days.

### Steps to reproduce

* Edit an ongoing client's preferences
* Try to specify meals default for a non-delivery day

**Comment by lamontfr** [comment]
@manumilou Based on the discussion with Jean-François on 2017-03-17, the expected behavior specified in this issue is correct.

My understanding of JF's requirements (for milestone SRoulant_2.0) is that : 
- Meal defaults and meal schedule are two different concepts and the UI should reflect this.
- Irrespective of delivery type (ongoing and episodic) the client preferences should always show the meal defaults, that is **what** the client said he wants in **his** meal for specific weekdays.
- For an ongoing delivery type only, the client preferences should show the also meal schedule, that is **when** (= on which weekdays) he wants **his** meal delivered.

**Comment by peakwinter** [comment]
From what I understand, pull #695 addresses most of the second bullet point but nothing from the other two. Let me know if that is the case and I can work on the other items later.

**Comment by lamontfr** [comment]
@peakwinter I appreciate your offer. I will ask Jean-François if he wants the changes done now and get back to you.

**Comment by lingxiaoyang** [comment]
@peakwinter  @lamontfr  Oops! I've merged PR #695 before reading your discussion here.

@lamontfr  Would you mind creating a new issue for the new requirements? Still, I think they are out of the scope of this issue itself.

**Comment by lamontfr** [comment]
@lingxiaoyang @peakwinter I created a new issue that will be required for Milestone 2.0, unless Jean-François says he needs it in Milestone 1.1.

**Comment by JeanFrancoisFournier** [comment]
If I understand these somewhat merged issues correctly, I definitely feel that the meal defaults and meal schedule should be decoupled both in the UI and in the logical architecture of the code. In this issue, the UI (issue 700) and Logic (issue 688) should be addressed together as a milestone 1.1
