### ISSUE TITLE
Enhance client scheduled status change UI

### ISSUE THREAD

**Issue by lingxiaoyang** [savoirfairelinux/sous-chef#717]
### Expected Behaviour

Wrote by JF in #685:

> Within the UI, we should be able to:
> 1# Cancel a future scheduled status change (i.e. client calls to cancel his planned vacation due to family emergency)
> 2# Cancel a current (ongoing) scheduled status change (client changes his mind in the middle of a meal delivery pause)
> 3# Lengthen a current (ongoing) scheduled status change (ie. prolonged hospitalisation)
> 4# Shorten a current (ongoing) scheduled status change (i.e Client is released from jail early for good conduct)
> 5# Lengthen a future scheduled status change
> 6# Shorten a future scheduled status change

This enhancement could easily bring confusion if simply added to the UI, because the scheduled changes are related with a client's actual status and vice versa. Needs discussion on how we define the backend behaviours.

### Actual Behaviour

Not implemented yet.

### Steps to reproduce

N/A

**Comment by lingxiaoyang** [comment]
What I propose:

1. As this ticket implies multiple possibilities of a status change, we should make sure that the page "Scheduled Status Changes" provides all these possibilities, including: adding a status change, editing a status change, deleting a status change, etc... 

2. The little yellow badge at the top-right corner can also be useful for making a quick status change, but we have to limit its functionalities:
  a. When there are pending status changes, the user may not modify the status using the badge. Instead, the badge should also display the next pending status change, and when the user clicks on it, redirect to "Scheduled Status Changes" page. 
  b. When there are no pending status changes, the badge can work as how it does now, prompting the status change window. But after confirming the change, the user should, in my opinion, be redirected to the "Scheduled Status Changes" page to verify the change.

3. Some limitations when modifying a scheduled status change:
  a. It should be impossible to modify a processed status change.
  b. The sequence of status changes should not be affected when the user makes a modification.
  c. It is only possible to delete the latest scheduled status change. 
  d. Status changes with an "error" status should be treated as "Processed", but with the option of retry. ([When will it be an error?](https://github.com/savoirfairelinux/sous-chef/blob/dev/src/member/models.py#L946-L966))


An example to illustrate 3a, 3b, and 3c:

We have the following status changes:

| Date    |   From   |  To   |   Status    |     UI |
| -------- | ---------- | ------ | ------------ | ------ |
| 2017/05/30 | Active | Paused | To be processed | **deletable, possible to be moved on any date after 2017/05/28**  |
| 2017/05/27 | Stop: contact | Active | To be processed | **not deletable, possible to be moved on any date between 2017/05/02 and 2017/05/29** |
| 2017/05/01 | Active | Stop: contact | To be processed | **not deletable, possible to be moved on any date between 2017/04/26 and 2017/05/26** |
| 2017/04/25 | Paused | Active | To be processed | **not deletable, possible to be moved on any date between today (2017/03/31 as of today) and 2017/04/30. If moved to today, process immediately** |
| 2017/02/01 | Active | Paused | Error | **impossible to modify. only retry** |
| 2017/01/01 | Stop: no contact | Active | Processed | **impossible to modify** |


4. When adding a new status change directly on "Scheduled Status Changes", it should be:
  a. later than the latest scheduled status change, or today, whichever is later.
  b. from the last status "To".

Please comment! Or I'd love to make a demo PR for it.

**Comment by lingxiaoyang** [comment]
@aaboffill  This proposition, however, will invalidate your PR #711 as it doesn't rely on the concept of "paired status changes", because it'll let the user directly manage the entries of scheduled status changes, and also unnecessary to remove the pair when we are deleting a scheduled status change.

**Comment by aaboffill** [comment]
Well, in order to reach the requirements of @JeanFrancoisFournier , I think that we need only to add the functionality to modify the `Scheduled Status Change`, to provide the needed flexibility.

Now, as @lingxiaoyang say, we need to keep in mind a lot of rules or restrictions. I think that the `django model` and the `way` that we use to manage the `Scheduled Status Change` behavior, brings some difficulties when we play with `Scheduled Status Change`. Some changes related to the `Django model` and the `concept` will be necessary to reach the goal, **it's my opinion**.

**My proposal:**

### About the Concept

- The `Scheduled Status Change` created automatically as relationship `pair`, when we fix a date to end the `Scheduled Status Change` period, it's created in order to ensure the regression to the departure status. In my appreciation, that's not really necessary. I think that the `pair` created is part of the elements that difficult the process. Instead, the `Scheduled Status Change` could be created with an `end date`. Every time that the `end date` is reached, the regression process to the departure status would be thrown. 
- The departure status, it's not really convenient to fix in the moment of the status schedule. We don't know if the current client status will be the real status in the moment to process the `Scheduled Status Change`. Instead, the departure status should be taken of the client status in the moment to execute the `Scheduled Status Change`. With this action, we will be ensure that if is necessary a regression, that regression will be processed to a valid status.
- Once we have a `Scheduled Status Change` with `date range`, is necessary to avoid some other `Scheduled Status Change` intercepts other `date range` previously scheduled. If we have that case, is necessary to modify the `Scheduled Status Change` that hinders the new schedule.
- I think that every `Scheduled Status Change` not finalized could be removed, even if that `Scheduled Status Change` is already started. Every time that we remove an `Scheduled Status Change`, the regression process to the departure status will be thrown if the `Scheduled Status Change` is ongoing. I think that remove/edit an `Scheduled Status Change` ended, does not make sense.
- Same as the previous point, we can modify an `Scheduled Status Change` while it is not finalized. In this case, the 'start date' **cannot be edited** if the `Scheduled Status Change` is ongoing. 

### Technical suggestions

- Remove the field `pair` into the model `ClientScheduledStatus`.
- Add `end date` to the model `ClientScheduledStatus`.
- Provide all needed test to validate the new concept.
- Implement the new concept.
- Invalidate all affected dates in the `JavaScript` calendar date, in order to improve the user experience. 


This is my humble opinion :)
Any comments about that @lingxiaoyang , @JeanFrancoisFournier , @manumilou

**Comment by lingxiaoyang** [comment]
@aaboffill  I think you'll also need another field to keep the original status. If I'm correct, the new ScheduledStatusChange model will be:

```python
class ScheduledStatusChange(Model):
    start_date = DateField()
    end_date = DateField(null=True)
    original_status = ChoiceField(Status, null=True)
    client = ForeignKey(Client)
    reason = TextField()
    process_status = ChoiceField(ProcessStatus)
```

And it distinguishes "permanent change" and "temporary change" by `end_date` and `original_status`; "processed change" and "future change" by `start_date`.

One problem I noticed is that we may lose track of processed permanent changes, because the `status_to` field is removed.

Perhaps we should also rename the model? It doesn't sound natural to me to have processed changes in a **Scheduled**StatusChange model.

**Comment by lingxiaoyang** [comment]
@aaboffill  Another idea: don't bother too much with the model `ClientScheduledStatus`. We simply keep the status change modal, and make it possible to **overwrite** any future scheduled changes.

If we take another look at the requirements:

> 1# Cancel a future scheduled status change (i.e. client calls to cancel his planned vacation due to family emergency)

This can be implemented by deleting a pair of scheduled changes.

Note: we should somehow let the admin know that there's a future status change.

> 2# Cancel a current (ongoing) scheduled status change (client changes his mind in the middle of a meal delivery pause)

This can be done in the status change modal, because it is an ongoing change. The admin can simply change the client's current status back to active, and this removes all future status changes.

Note: the same, notify admin that the client has an ongoing change.

> 3# Lengthen a current (ongoing) scheduled status change (ie. prolonged hospitalisation)

Also, in the status change modal, set the start date in the future.

Note: the admin should be prompted of the details of this ongoing change.

> 4# Shorten a current (ongoing) scheduled status change (i.e Client is released from jail early for good conduct)

Same as 3#.

> 5# Lengthen a future scheduled status change

In the status change modal, reset the start date and the end date.

> 6# Shorten a future scheduled status change

Same as 5#.

How do you think?

**Comment by aaboffill** [comment]
@lingxiaoyang adding some changes to your proposed class. I don't still happy with the name, but maybe sound a little better. I added some changes on the status attributes.

```python
class FutureStatusChange(Model):
    start_date = DateField()
    end_date = DateField(null=True)
    status = ChoiceField(Status)
    regression_status = ChoiceField(Status, null=True)
    client = ForeignKey(Client)
    reason = TextField()
    process_status = ChoiceField(ProcessStatus)
```

About your last comment, maybe it's a little more quick to implement, maybe don't need migrations, but I think that keep the process not natural. 
Depend what is better in this case, add the pertinent changes to reach the goal with less changes, or made the changes to improve the solution and to build a solution more natural and simple to be maintained.

**Comment by lingxiaoyang** [comment]
@aaboffill 
> that keeps the process less natural

I didn't understand what you refer to by "natural". Can you elaborate more on this?

**Comment by aaboffill** [comment]
Sure! @lingxiaoyang , that means the following:
Keeping the `pair` relationship, instead of a simple `end_date`, makes the process more complex, more difficult to maintain future changes.

**Comment by lingxiaoyang** [comment]
@aaboffill How about removing the `pair` relationship? My point was also that we don't allow too many scheduled status changes on a client - at most two, a scheduled start and a scheduled end. For the given 6 requirements, this would be sufficient.

But if we need to implement multiple status changes or more complex cases, we'll have to let admin work on the scheduled changes page. Generally, I think there should be some sort of communication between the admin and their client when the client is resumed, instead of planning all changes in the beginning. In this case, it might be safe to do it in the simple way?

**Comment by aaboffill** [comment]
I don't know @lingxiaoyang , is very possible that I haven't the enough knowledge about the Sous-Chef logic, but if our  discussion has been good to clarify how you can proceed with this issue, it's a good chance for you to continue and propose a fix. :+1:

**Comment by lingxiaoyang** [comment]
**Progress**

UI: Inform user if there are upcoming changes. Menus are different.
![image](https://cloud.githubusercontent.com/assets/8630726/25152966/cbb39486-2458-11e7-851e-b93af5e05451.png)

![image](https://cloud.githubusercontent.com/assets/8630726/25152971/d17980c4-2458-11e7-8c21-aee3b110a06d.png)

UI: Inform user if there's an error or a potential error. (Error status or the change didn't happen. The screenshot is just for showing the look and feel.)
![image](https://cloud.githubusercontent.com/assets/8630726/25153116/6395c63e-2459-11e7-9c98-9d4adb5d85bd.png)
